TaskManagerToDo/Models/ErrorViewModel.cs
using System;

namespace TaskManagerToDo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TaskManagerToDo/Models/ToDoTask.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TaskManagerToDo.Identity;

namespace TaskManagerToDo.Models
{
    public class ToDoTask
    {
        public int Id { get; set; }

        [Required]
        public string Description { get; set; }

        [DisplayName("Due Date")]
        public DateTime DueDate { get; set; }

        [DisplayName("Complete?")]
        public bool IsComplete { get; set; }

        [ForeignKey("UserID")]
        public ApplicationUser User { get; set; }
        public string UserID { get; set; }
    }
}

TaskManagerToDo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TaskManagerToDo.Models;

namespace TaskManagerToDo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TaskManagerToDo/Controllers/ToDoTasksController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TaskManagerToDo.Data;
using TaskManagerToDo.Identity;
using TaskManagerToDo.Models;
using TaskManagerToDo.Service.Interface;

namespace TaskManagerToDo.Controllers
{
    public class ToDoTasksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToDoTaskService _service;
        private readonly UserManager<ApplicationUser> _userManager;

        public ToDoTasksController(IToDoTaskService service, UserManager<ApplicationUser> userManager)
        {
            _service = service;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string searchTerm = "")
        {
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser == null)
            {
                return View();
            }

            return View(await _service.GetTasks(currentUser, searchTerm));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoTask = await _service.GetTaskById((int)id);
            if (toDoTask == null)
            {
                return NotFound();
            }

            return View(toDoTask);
        }

        public async Task<IActionResult> Create()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var toDoTask = new ToDoTask()
            {
                UserID = currentUser.Id
            };

            return View(toDoTask);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ToDoTask toDoTask)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateTask(toDoTask);

                return RedirectToAction(nameof(Index));
            }
            return View(toDoTask);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoTask = await _service.GetTaskById((int)id);
            if (toDoTask == null)
            {
                return NotFound();
            }
            return View(toDoTask);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ToDoTask toDoTask)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    toDoTask = await _service.UpdateTask(toDoTask);
                }
                catch (Exception e)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(toDoTask);
        }

        public async Task<IActionResult> Delete(int id)
        {
            return View(await _service.GetTaskById(id));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var toDoTask = await _service.DeleteTask((int) id);

            return RedirectToAction(nameof(Index));
        }
    }
}

TaskManagerToDo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Generic To Do App</h4>
        <a asp-action="Index" asp-controller="ToDoTasks">Add stuff to your to-do list.</a>
    </div>
</div>

TaskManagerToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Generic To Do App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Generic To Do App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoTasks" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Generic To Do App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TaskManagerToDo/Views/ToDoTasks/Create.cshtml
@model TaskManagerToDo.Models.ToDoTask


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>New Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsComplete" /> @Html.DisplayNameFor(model => model.IsComplete)
                </label>
            </div>
            @Html.HiddenFor(x => x.UserID)
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskManagerToDo/Views/ToDoTasks/Delete.cshtml
@model TaskManagerToDo.Models.ToDoTask

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDoTask</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsComplete)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TaskManagerToDo/Views/ToDoTasks/Details.cshtml
@model TaskManagerToDo.Models.ToDoTask

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsComplete)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TaskManagerToDo/Views/ToDoTasks/Edit.cshtml
@model TaskManagerToDo.Models.ToDoTask

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDoTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            @Html.HiddenFor(x => x.UserID)
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsComplete" /> @Html.DisplayNameFor(model => model.IsComplete)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskManagerToDo/Views/ToDoTasks/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using TaskManagerToDo.Identity
@model IEnumerable<TaskManagerToDo.Models.ToDoTask>
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Index";
}

@if (SignInManager.IsSignedIn(User))
{
    <h1>Task List</h1>
    <p>
        <a asp-action="Create">Create New</a>
    </p>

    <div class="row">
        <div class="col-6">
            <div class="input-group mb-3">
                <input type="text" id="txtSearch" class="form-control" placeholder="Search by description" aria-label="Recipient's username" aria-describedby="basic-addon2">
                <button class="btn btn-primary" id="btnSearch">Search</button>
            </div>
        </div>
        <div class="col-6"></div>
    </div>

    @if (Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DueDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsComplete)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DueDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsComplete)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">No Tasks!</h4>
            <p>Create a new task and it will show on the list.</p>
        </div>
    }

}
else
{
    <div class="alert alert-info" role="alert">
        <h4 class="alert-heading">Please log in!</h4>
        <p>Please log in to view your task list. Please register if you do not have an account.</p>
    </div>
}

<script>
    $(document).ready(function () {

        $("#btnSearch").click(function() {
            var searchTerm = $("#txtSearch").val();

            if (searchTerm != '') {
                document.location = '@Url.Action("Index", "ToDoTasks")?searchTerm=' + searchTerm;
            }
        });

    });
</script>